// src/constants/tools.ts

import {
  FilePlus, Scissors, Archive, FileOutput, FileType, FileText,
  Unlock, Lock, RotateCw, FileImage, Image, FileHeart, Files, Link as LinkIcon, LucideProps,
  Crop, Droplets
} from "lucide-react";

export type ToolCategory = "Organize" | "Optimize" | "Convert" | "Edit" | "Security";

export const iconMap: { [key: string]: React.ElementType<LucideProps> } = {
  FilePlus, Scissors, Archive, FileOutput, FileType, FileText,
  Unlock, Lock, RotateCw, FileImage, Image, FileHeart, Files, LinkIcon,
  Crop, Droplets
};

export interface Tool {
  value: string;
  label: string;
  h1: string;
  description: string;
  category: ToolCategory;
  icon: keyof typeof iconMap;
  color: string;
  metaTitle: string;
  metaDescription: string;
  metaKeywords: string;
  steps: string[];
  isBrowserOnly: boolean;
  isMultiFile: boolean;
  faqs: { question: string; answer:string; }[];
}

type ToolMap = {
  [key: string]: Tool;
};

export const tools: ToolMap = {
  // --- WORKING TOOLS (USER-SPECIFIED ORDER) ---
  "merge-pdf": { value: "merge-pdf", label: "Merge PDF", h1: "Merge PDF Online", description: "Combine multiple PDF files into one instantly. Fast, free, and secure online PDF merger.", category: "Organize", icon: 'FilePlus', color: "#4A90E2", metaTitle: "Merge PDF Online – Free & Secure", metaDescription: "Combine multiple PDF files into one instantly. Fast, free, and secure online PDF merger.", metaKeywords: "merge pdf, combine pdf, pdf joiner, unite pdf", steps: ["Upload your PDFs", "Drag and drop to order them", "Click 'Merge PDF' to combine", "Download your merged file"], isBrowserOnly: true, isMultiFile: true, faqs: [] },
  "split-pdf": { value: "split-pdf", label: "Split PDF", h1: "Split PDF Online", description: "Separate PDF pages or extract sections easily. Free, secure, and fast PDF splitter.", category: "Organize", icon: 'Scissors', color: "#50E3C2", metaTitle: "Split PDF Online – Extract Pages Free", metaDescription: "Separate PDF pages or extract sections easily. Free, secure, and fast PDF splitter.", metaKeywords: "split pdf, pdf cutter, extract pdf pages", steps: ["Upload your PDF", "Select the pages or ranges to split", "Click 'Split PDF'", "Download your new files in a ZIP archive"], isBrowserOnly: true, isMultiFile: false, faqs: [] },
  "compress-pdf": { value: "compress-pdf", label: "Compress PDF", h1: "Compress PDF Online", description: "Shrink PDF file size without losing quality. Quick, secure, and free online PDF compressor.", category: "Optimize", icon: 'Archive', color: "#F8E71C", metaTitle: "Compress PDF Online – Reduce File Size", metaDescription: "Shrink PDF file size without losing quality. Quick, secure, and free online PDF compressor.", metaKeywords: "compress pdf, reduce pdf size, shrink pdf, pdf optimizer", steps: ["Upload your PDF", "Choose a compression level", "Click 'Compress PDF'", "Download your smaller, optimized PDF file"], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "organize-pdf": { value: "organize-pdf", label: "Organize PDF", h1: "Organize PDF Pages – Free Online Tool", description: "Reorder, arrange, and manage PDF pages effortlessly. Free and secure.", category: "Organize", icon: 'Files', color: "#4A90E2", metaTitle: "Organize PDF Pages – Free Online Tool", metaDescription: "Reorder, arrange, and manage PDF pages effortlessly. Free and secure.", metaKeywords: "organize pdf, sort pdf pages, delete pdf pages, reorder pdf", steps: ["Upload your PDF", "Drag pages to reorder them, or use the delete button", "Click 'Organize PDF'", "Download the modified file"], isBrowserOnly: true, isMultiFile: false, faqs: [] },
  "rotate-pdf": { value: "rotate-pdf", label: "Rotate PDF", h1: "Rotate PDF Pages – Free Online Tool", description: "Rotate and flip PDF pages easily. Free, secure, and simple to use online tool.", category: "Edit", icon: 'RotateCw', color: "#F5A623", metaTitle: "Rotate PDF Pages – Free Online Tool", metaDescription: "Rotate and flip PDF pages easily. Free, secure, and simple to use online tool.", metaKeywords: "rotate pdf, fix pdf orientation, pdf rotator", steps: ["Upload your PDF", "Choose to rotate all pages or select specific ones", "Set the rotation angle (90°, 180°, 270°)", "Download your rotated PDF"], isBrowserOnly: true, isMultiFile: false, faqs: [] },
  "protect-pdf": { value: "protect-pdf", label: "Protect PDF", h1: "Protect PDF with Password – Free Online", description: "Secure your PDF by adding a password. Lock PDFs online safely and for free.", category: "Security", icon: 'Lock', color: "#000000", metaTitle: "Protect PDF with Password – Free Online", metaDescription: "Secure your PDF by adding a password. Lock PDFs online safely and for free.", metaKeywords: "protect pdf, password protect pdf, encrypt pdf", steps: ["Upload your PDF", "Set a strong password", "Click 'Protect PDF'", "Download your encrypted file"], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "unlock-pdf": { value: "unlock-pdf", label: "Unlock PDF", h1: "Unlock PDF – Remove Password Online", description: "Remove passwords from locked PDFs instantly. Free, safe, and quick PDF unlocker.", category: "Security", icon: 'Unlock', color: "#9013FE", metaTitle: "Unlock PDF – Remove Password Online", metaDescription: "Remove passwords from locked PDFs instantly. Free, safe, and quick PDF unlocker.", metaKeywords: "unlock pdf, remove pdf password, pdf password remover", steps: ["Upload your protected PDF", "Enter the password", "Click 'Unlock PDF'", "Download your password-free PDF"], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "image-to-pdf": { value: "image-to-pdf", label: "Image to PDF", h1: "Image to PDF Converter – JPG/PNG to PDF", description: "Convert JPG, PNG, and other images into PDF documents easily. Free and secure.", category: "Convert", icon: 'Image', color: "#BD10E0", metaTitle: "Image to PDF Converter – JPG/PNG to PDF", metaDescription: "Convert JPG, PNG, and other images into PDF documents easily. Free and secure.", metaKeywords: "image to pdf, jpg to pdf, png to pdf", steps: ["Upload your JPG, PNG, or other image files", "Drag to reorder them if needed", "Click 'Convert to PDF'", "Download your new PDF document"], isBrowserOnly: false, isMultiFile: true, faqs: [] },
  "pdf-to-image": { value: "pdf-to-image", label: "PDF to Image", h1: "PDF to JPG/PNG – Convert PDF to Images", description: "Extract pages from PDFs and save them as JPG or PNG images. Free online converter.", category: "Convert", icon: 'FileImage', color: "#BD10E0", metaTitle: "PDF to Image – Convert PDF to JPG", metaDescription: "Extract pages from PDFs and save them as JPG or PNG images. Free online converter.", metaKeywords: "pdf to jpg, pdf to image, convert pdf to png", steps: ["Upload your PDF", "Click 'Convert to Images'", "Download your images in a ZIP file"], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "add-watermark": { value: "add-watermark", label: "Add Watermark", h1: "Add Watermark to PDF", description: "Stamp your PDFs with a text or image watermark. Customize typography, transparency, and position.", category: "Edit", icon: 'Droplets', color: "#0077B6", metaTitle: "Add Watermark to PDF – Free & Secure", metaDescription: "Easily add a text or image watermark to your PDF files. Customize placement, transparency, rotation, and more with our free online tool.", metaKeywords: "add watermark pdf, pdf watermark, stamp pdf, text watermark, image watermark", steps: ["Upload your PDF file.", "Choose to add a text or image watermark.", "Customize the style, position, and transparency.", "Click 'Add Watermark' and download your protected file."], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "edit-pdf": { value: "edit-pdf", label: "Edit PDF", h1: "Edit PDF Online – Free PDF Editor", description: "Edit text, images, and pages in PDF files instantly. Free and user-friendly PDF editor.", category: "Edit", icon: 'FileText', color: "#7ED321", metaTitle: "Edit PDF Online – Free PDF Editor", metaDescription: "Edit text, images, and pages in PDF files instantly. Free and user-friendly PDF editor.", metaKeywords: "edit pdf, pdf editor, annotate pdf, modify pdf", steps: ["Upload your PDF", "Use the toolbar to add text, images, or shapes", "Save your changes", "Download the edited PDF"], isBrowserOnly: true, isMultiFile: false, faqs: [] },
  "crop-pdf": { value: "crop-pdf", label: "Crop PDF", h1: "Crop PDF Files Online", description: "Visually select and trim the margins of your PDF pages. Fast, simple, and free.", category: "Edit", icon: 'Crop', color: "#E54D2E", metaTitle: "Crop PDF Online – Free PDF Cropping Tool", metaDescription: "Easily crop your PDF files online. Select the area you want to keep and remove the rest. A free, secure, and visual PDF cropping tool.", metaKeywords: "crop pdf, pdf cropper, trim pdf, resize pdf pages", steps: ["Upload your PDF file.", "An adjustable crop box will appear on your page.", "Drag the corners and sides of the box to define the area you want to keep.", "Choose to apply the crop to the current page or all pages.", "Click 'Crop PDF' and download your new file."], isBrowserOnly: false, isMultiFile: false, faqs: [] },

  // --- NON-WORKING / COMING SOON TOOLS ---
  "pdf-to-word": { value: "pdf-to-word", label: "PDF to Word", h1: "Convert PDF to Word Online", description: "Convert PDFs into editable Word documents in seconds. Accurate, free, and easy PDF to Word converter.", category: "Convert", icon: 'FileType', color: "#2B78E4", metaTitle: "Convert PDF to Word Online – Free", metaDescription: "Convert PDFs into editable Word documents in seconds. Accurate, free, and easy PDF to Word converter.", metaKeywords: "pdf to word, convert pdf to word, pdf to docx", steps: [], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "word-to-pdf": { value: "word-to-pdf", label: "Word to PDF", h1: "Word to PDF Converter – Free Online", description: "Convert Word documents (DOCX) to PDF with one click. Free, secure, and reliable.", category: "Convert", icon: 'FileOutput', color: "#2B78E4", metaTitle: "Word to PDF Converter – Free Online", metaDescription: "Convert Word documents (DOCX) to PDF with one click. Free, secure, and reliable.", metaKeywords: "word to pdf, docx to pdf, convert word to pdf", steps: [], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "pdf-to-excel": { value: "pdf-to-excel", label: "PDF to Excel", h1: "PDF to Excel Converter – Free Online", description: "Extract tables and convert PDF files into Excel spreadsheets instantly.", category: "Convert", icon: 'FileType', color: "#1D6F42", metaTitle: "PDF to Excel Converter – Free Online", metaDescription: "Extract tables and convert PDF files into Excel spreadsheets instantly.", metaKeywords: "pdf to excel, convert pdf to excel, pdf to xlsx", steps: [], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "excel-to-pdf": { value: "excel-to-pdf", label: "Excel to PDF", h1: "Excel to PDF Converter – Free Online", description: "Convert Excel sheets to PDF quickly and securely. Free online Excel to PDF tool.", category: "Convert", icon: 'FileOutput', color: "#1D6F42", metaTitle: "Excel to PDF Converter – Free Online", metaDescription: "Convert Excel sheets to PDF quickly and securely. Free online Excel to PDF tool.", metaKeywords: "excel to pdf, xlsx to pdf, convert excel to pdf", steps: [], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "pdf-to-powerpoint": { value: "pdf-to-powerpoint", label: "PDF to PowerPoint", h1: "PDF to PPT Converter – Free Online", description: "Convert PDFs to editable PowerPoint slides in seconds. Free and accurate PDF to PPT tool.", category: "Convert", icon: 'FileType', color: "#D04423", metaTitle: "PDF to PPT Converter – Free Online", metaDescription: "Convert PDFs to editable PowerPoint slides in seconds. Free and accurate PDF to PPT tool.", metaKeywords: "pdf to powerpoint, pdf to ppt, convert pdf to ppt", steps: [], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "powerpoint-to-pdf": { value: "powerpoint-to-pdf", label: "PowerPoint to PDF", h1: "PPT to PDF Converter – Free Online", description: "Turn PowerPoint presentations into PDFs instantly. Free, secure, and simple PPT to PDF tool.", category: "Convert", icon: 'FileOutput', color: "#D04423", metaTitle: "PPT to PDF Converter – Free Online", metaDescription: "Turn PowerPoint presentations into PDFs instantly. Free, secure, and simple PPT to PDF tool.", metaKeywords: "powerpoint to pdf, ppt to pdf, convert ppt to pdf", steps: [], isBrowserOnly: false, isMultiFile: false, faqs: [] },
  "esign-pdf": { value: "esign-pdf", label: "eSign PDF", h1: "Sign PDF Online – Add Digital Signatures", description: "Add your electronic signature to PDFs quickly. Free and secure PDF signing tool.", category: "Security", icon: 'FileHeart', color: "#FF4136", metaTitle: "Sign PDF Online – Add Digital Signatures", metaDescription: "Add your electronic signature to PDFs quickly. Free and secure PDF signing tool.", metaKeywords: "esign pdf, sign pdf, digital signature, electronic signature", steps: [], isBrowserOnly: true, isMultiFile: false, faqs: [] },
};

export const toolArray: Tool[] = Object.values(tools);

export const categories: ToolCategory[] = ["Organize", "Optimize", "Convert", "Edit", "Security"];
